Redirect warnings and error messages to stderr.

diff --git a/elf/ldd.bash.in b/elf/ldd.bash.in
--- a/elf/ldd.bash.in
+++ b/elf/ldd.bash.in
@@ -35,7 +35,7 @@ while test $# -gt 0; do
   case "$1" in
   --v | --ve | --ver | --vers | --versi | --versio | --version)
     echo $"ldd (GNU libc) @VERSION@
-Copyright (C) 1996, 1997 Free Software Foundation, Inc.
+Copyright (C) 1996, 1997, 1998 Free Software Foundation, Inc.
 This is free software; see the source for copying conditions.  There is NO
 warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE."
     exit 0
@@ -93,7 +93,8 @@ case $# in
     exit 1
   elif test -r "$file"; then
     test -x "$file" ||
-    echo $"ldd: warning: you do not have execution permission for" "\`$file'"
+    echo $"\
+ldd: warning: you do not have execution permission for" "\`$file'" >&2
       if ${RTLD} --verify "$file"; then
 	LD_TRACE_LOADED_OBJECTS=1 exec ${RTLD} ${RELOCS} "$file" || exit 1
       else
@@ -101,7 +102,7 @@ case $# in
 	exit 1
       fi
   else
-    echo $"ldd: error: you do not have read permission for" "\`$file'"
+    echo $"ldd: error: you do not have read permission for" "\`$file'" >&2
     exit 1
   fi
   exit
@@ -122,7 +123,7 @@ case $# in
       result=1
     elif test -r "$file"; then
       test -x "$file" || echo $"\
-ldd: warning: you do not have execution permission for" "\`$file'"
+ldd: warning: you do not have execution permission for" "\`$file'" >&2
       if ${RTLD} --verify "$file"; then
 	LD_TRACE_LOADED_OBJECTS=1 ${RTLD} ${RELOCS} "$file" || result=1
       else
@@ -130,7 +131,7 @@ ldd: warning: you do not have execution permission for" "\`$file'"
 	result=1
       fi
     else
-      echo $"ldd: error: you do not have read permission for" "\`$file'"
+      echo $"ldd: error: you do not have read permission for" "\`$file'" >&2
       result=1
     fi
   done
diff --git a/elf/ldd.sh.in b/elf/ldd.sh.in
--- a/elf/ldd.sh.in
+++ b/elf/ldd.sh.in
@@ -31,7 +31,7 @@ while test $# -gt 0; do
   case "$1" in
   --v | --ve | --ver | --vers | --versi | --versio | --version)
     echo 'ldd (GNU libc) @VERSION@
-Copyright (C) 1996, 1997 Free Software Foundation, Inc.
+Copyright (C) 1996, 1997, 1998 Free Software Foundation, Inc.
 This is free software; see the source for copying conditions.  There is NO
 warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.'
     exit 0
@@ -92,7 +92,8 @@ Try \`ldd --help' for more information."
   else
     if test -r "$file"; then
       test -x "$file" ||
-	echo "ldd: warning: you do not have execution permission for \`$file'"
+	echo "\
+ldd: warning: you do not have execution permission for \`$file'" >&2
       if ${RTLD} --verify "$file"; then
 	LD_TRACE_LOADED_OBJECTS=1 exec ${RTLD} ${RELOCS} "$file" || exit 1
       else
@@ -100,7 +101,7 @@ Try \`ldd --help' for more information."
 	exit 1
       fi
     else
-      echo "ldd: error: you do not have read permission for \`$file'"
+      echo "ldd: error: you do not have read permission for \`$file'" >&2
       exit 1
     fi
   fi
@@ -123,7 +124,7 @@ Try \`ldd --help' for more information."
     else
       if test -r "$file"; then
 	test -x "$file" || echo "\
-ldd: warning: you do not have execution permission for \`$file'"
+ldd: warning: you do not have execution permission for \`$file'" >&2
 	if ${RTLD} --verify "$file"; then
 	  LD_TRACE_LOADED_OBJECTS=1 ${RTLD} ${RELOCS} "$file" || result=1
 	else
@@ -131,7 +132,7 @@ ldd: warning: you do not have execution permission for \`$file'"
 	  result=1
 	fi
       else
-	echo "ldd: error: you do not have read permission for \`$file'"
+	echo "ldd: error: you do not have read permission for \`$file'" >&2
 	result=1
       fi
     fi
