chore: automatically release

diff --git a/.github/workflows/glibc.yml b/.github/workflows/glibc.yml
--- a/.github/workflows/glibc.yml
+++ b/.github/workflows/glibc.yml
@@ -1,15 +1,76 @@
 name: glibc
 
-on: [push, pull_request]
-#   push: 
-#     tags: 
-#       - "v*"
+# on: [push, pull_request]
+on:
+  push: 
+    tags: 
+      - "v*"
 
 jobs:
-  release: 
+  meta:
+    runs-on: ubuntu-latest
+    outputs:
+      tag: ${{ steps.set_tag.outputs.tag }}
+      prerelease: ${{ steps.set_pre.outputs.prerelease }}
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+        with:
+          path: temp
+          show-progress: false
+
+      - name: Fetch history
+        if: ${{ !startsWith(github.ref, 'refs/pull/') }}
+        run: |
+          git init
+          cp $GITHUB_WORKSPACE/temp/.git/config ./.git
+          rm -rf $GITHUB_WORKSPACE/temp
+          # git config remote.origin.fetch '+refs/*:refs/*'
+          git fetch --filter=tree:0 # --update-head-ok
+          git reset --hard origin/$(git branch --show-current) || true
+          git checkout ${{ github.ref_name }}
+
+      - name: Set tag
+        id: set_tag
+        run: |
+          ${{ startsWith(github.ref, 'refs/pull/') && 'cd temp' || '' }}
+          echo tag=$(git describe --tags --match "v*" ${{ github.ref }} || git rev-parse --short HEAD) | tee -a $GITHUB_OUTPUT
+          exit ${PIPESTATUS[0]}
+
+      - name: Judge pre-release
+        id: set_pre
+        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
+        run: |
+          if [[ '${{ steps.set_tag.outputs.tag }}' =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo prerelease=false | tee -a $GITHUB_OUTPUT
+          else
+            echo prerelease=true | tee -a $GITHUB_OUTPUT
+          fi
+
+      - name: Generate changelog
+        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
+        run: |
+          this_tag=${{ steps.set_tag.outputs.tag }}
+          if [[ '${{ steps.set_pre.outputs.prerelease }}' != 'false' ]]; then
+            last_tag=$(git describe --tags --match "v*" --abbrev=0 --exclude='${{ steps.set_tag.outputs.tag }}')
+          else
+            last_tag=$(git describe --tags --match "v*" --abbrev=0 --exclude='${{ steps.set_tag.outputs.tag }}' --exclude='*-*')
+          fi
+          echo >> CHANGELOG.md
+          echo "**Full Changelog**: [$last_tag -> $this_tag](${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/compare/${last_tag}...${this_tag})" >> CHANGELOG.md
+
+      - name: Upload changelog to Github
+        uses: actions/upload-artifact@v4
+        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
+        with:
+          name: changelog
+          path: CHANGELOG.md
+
+  build: 
+    needs: meta
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v4
       - name: Install Dependencies
         run: |
           bash ./install_deps.sh
@@ -28,5 +89,35 @@ jobs:
           name: glibc
           path: |
             release/*.tar.gz
-          
+  release:
+    if: startsWith(github.ref, 'refs/tags/v')
+    needs: [meta, build]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Download glibc from Github
+        uses: actions/download-artifact@v4
+        with:
+          path: assets
+
+      # - name: Cleanup files
+      #   run: |
+      #     mv -vf assets/changelog/* .
+      #     rm -rf assets/MAACore-macos-*
+      #     cd assets
+      #     # find . -type f | xargs mv -fvt .
+      #     find . -type f | while read f; do mv -fvt . $f; done
+
+      - name: Release to Github
+        uses: softprops/action-gh-release@v1
+        with:
+          body_path: assets/changelog/CHANGELOG.md
+          files: |
+            assets/*
+          prerelease: ${{ needs.meta.outputs.prerelease != 'false' }}
+
+      # - name: Trigger secondary workflows # ref: https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow
+      #   run: |
+      #     gh workflow run --repo $GITHUB_REPOSITORY release-ota
+      #   env:
+      #     GH_TOKEN: ${{ secrets.MISTEOWORKFLOW }}
         
